spring:
  application:
    name: AMF-CI
#  profiles:
#    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
